import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f6f8",
    padding: 24,
    paddingBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1a1a1a",
    marginBottom: 12,
  },
  text: {
    fontSize: 16,
    color: "#555",
    lineHeight: 24,
    marginBottom: 28,
  },
  reminderCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 22,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  reminderTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 8,
  },
  reminderDesc: {
    fontSize: 14,
    color: "#666",
    lineHeight: 22,
    marginBottom: 20,
  },
  reminderDate: {
    fontSize: 15,
    fontWeight: "700",
    color: "#e85a4a",
  },
  ticketCard: {
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 24,
    marginTop: 20,
    marginBottom: 28,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  ticketImage: {
    marginBottom: 16,
    borderRadius: 14,
    overflow: "hidden",
  },
  ticketImageImg: {
    width: "100%",
    height: 140,
    borderRadius: 14,
  },
  ticketImagePlaceholder: {
    height: 140,
    backgroundColor: "#f8f6f8",
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  ticketEventName: {
    fontSize: 28,
    fontWeight: "800",
    color: "#333",
    letterSpacing: 2,
    marginBottom: 16,
  },
  ticketDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  ticketCol: {
    flex: 1,
  },
  ticketLabel: {
    fontSize: 11,
    color: "#666",
    marginBottom: 4,
  },
  ticketValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#333",
  },
  barcodeContainer: {
    alignItems: "center",
    paddingTop: 16,
    borderTopWidth: 1,
    borderStyle: "dashed",
    borderTopColor: "#999",
  },
  barcodeLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 8,
  },
  barcodeDashed: {
    height: 1,
    width: "100%",
    marginBottom: 12,
  },
  barcodeBars: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    height: 48,
    gap: 1,
  },
  barcodeBar: {
    height: "100%",
    backgroundColor: "#333",
    borderRadius: 1,
  },
  ticketBtn: {
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: "#e85a4a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  ticketBtnGradient: {
    paddingVertical: 16,
    alignItems: "center",
  },
  ticketBtnText: {
    color: "white",
    fontWeight: "600",
    fontSize: 16,
  },
  button: {
    backgroundColor: "#e85a4a",
    borderRadius: 16,
    padding: 18,
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
  },
});
